version: '3.8'

services:
  llm-inference:
    image: tahaabolhasani/llm-inference-image
    ports:
      - "8080:5000"
    environment:
      - METRICS_LOG_FILE=inside_compose_inference_metrics.csv
    volumes:
      - ./compose_inference_metrics.csv:/app/inside_compose_inference_metrics.csv

